'use strict';

/** Corpo Markdown — versões EN/ES (resumo operacional; o jurídico definitivo pode substituir no admin). */

exports.TERMS_EN = [
  '# BrSpark Platform — Terms of Use',
  '',
  '**Version 1.0 — Effective March 23, 2025**',
  '',
  'Welcome to BrSpark. By creating an account and using our services, you agree to these Terms of Use.',
  '',
  '## 1. Acceptance',
  'Access and use are conditioned on your acceptance of these terms.',
  '',
  '## 2. Service',
  'BrSpark is a SaaS platform for managing personal and business assets (inventory, documents, insurance, and related features).',
  '',
  '## 3. Account',
  'You must provide accurate information, keep credentials confidential, and notify **support@brspark.com** of unauthorized use.',
  '',
  '## 4. Acceptable use',
  'You may not misuse the platform, access others’ data, reverse engineer, or use the service unlawfully.',
  '',
  '## 5. Plans & billing',
  'Paid plans may change with **30 days’ notice**. Refunds follow applicable law.',
  '',
  '## 6. Privacy',
  'Personal data is processed under our **Privacy Policy** (LGPD & GDPR-aligned).',
  '',
  '## 7. Intellectual property',
  'BrSpark retains rights to the platform; data you enter remains yours.',
  '',
  '## 8. Limitation of liability',
  'To the extent permitted by law, liability is limited to fees paid in the **last 3 months**.',
  '',
  '## 9. Termination',
  'You may close your account in settings. Data may be retained as described in the Privacy Policy.',
  '',
  '## 10. Law & venue',
  'Governed by the laws of **Brazil**; venue: **São Paulo / SP**, unless mandatory consumer law says otherwise.',
  '',
  '---',
  '📧 **Contact**: support@brspark.com | 🌐 https://www.brspark.com',
].join('\n');

exports.PRIVACY_EN = [
  '# BrSpark — Privacy Policy',
  '',
  '**Version 1.0 — Effective March 23, 2025**',
  '',
  'BrSpark Tecnologia Ltda. is committed to protecting your privacy. This Policy describes how we collect, use, and safeguard personal data, in line with **LGPD (Brazil)** and **GDPR (EU)** where applicable.',
  '',
  '## 1. Controller',
  '**BrSpark Tecnologia Ltda.** — São Paulo, Brazil. DPO: **dpo@brspark.com**.',
  '',
  '## 2. Data we collect',
  '- Registration data (name, email, password hash);',
  '- Asset and operational data you choose to store;',
  '- Device, security, and diagnostic logs as needed to run the service.',
  '',
  '## 3. Purposes & legal bases',
  'Account creation, service delivery, security, fraud prevention, legal compliance, and (where required) consent for notifications.',
  '',
  '## 4. Sharing',
  'We **do not sell** personal data. We use infrastructure providers and share when required by law.',
  '',
  '## 5. Security',
  'Encryption in transit (TLS) and at rest where applicable; passwords stored using strong hashing.',
  '',
  '## 6. Retention',
  'Retention periods depend on account status, legal obligations, and operational needs (see detailed policy in Portuguese if needed).',
  '',
  '## 7. Your rights',
  'Access, correction, deletion, portability, objection, and consent withdrawal where applicable — contact **dpo@brspark.com**.',
  '',
  '## 8. Changes',
  'Material changes will be notified with reasonable advance notice.',
  '',
  '---',
  '📧 **DPO**: dpo@brspark.com | 🌐 https://www.brspark.com',
].join('\n');

exports.TERMS_ES = [
  '# Plataforma BrSpark — Términos de uso',
  '',
  '**Versión 1.0 — Vigencia a partir del 23 de marzo de 2025**',
  '',
  'Bienvenido a BrSpark. Al crear una cuenta y utilizar nuestros servicios, aceptas estos Términos de uso.',
  '',
  '## 1. Aceptación',
  'El acceso y el uso están supeditados a la aceptación de estos términos.',
  '',
  '## 2. Servicio',
  'BrSpark es una plataforma SaaS para la gestión de activos personales y empresariales (inventario, documentos, seguros y funciones relacionadas).',
  '',
  '## 3. Cuenta',
  'Debes proporcionar datos veraces, mantener la confidencialidad de las credenciales y notificar usos no autorizados a **support@brspark.com**.',
  '',
  '## 4. Uso aceptable',
  'No debes hacer un uso indebido de la plataforma, acceder a datos de terceros, realizar ingeniería inversa ni utilizar el servicio de forma ilícita.',
  '',
  '## 5. Planes y facturación',
  'Los planes de pago pueden cambiar con **aviso previo de 30 días**. Los reembolsos se rigen por la ley aplicable.',
  '',
  '## 6. Privacidad',
  'El tratamiento de datos personales se rige por nuestra **Política de privacidad** (alineada con LGPD y GDPR).',
  '',
  '## 7. Propiedad intelectual',
  'BrSpark conserva los derechos sobre la plataforma; los datos que introduces siguen siendo tuyos.',
  '',
  '## 8. Limitación de responsabilidad',
  'En la medida en que lo permita la ley, la responsabilidad se limita a las tarifas abonadas en los **últimos 3 meses**.',
  '',
  '## 9. Resolución',
  'Puedes cerrar tu cuenta en la configuración. La conservación de datos se describe en la Política de privacidad.',
  '',
  '## 10. Ley y fuero',
  'Se rigen por las leyes de **Brasil**; fuero: **São Paulo / SP**, salvo normas imperativas del consumidor.',
  '',
  '---',
  '📧 **Contacto**: support@brspark.com | 🌐 https://www.brspark.com',
].join('\n');

exports.PRIVACY_ES = [
  '# BrSpark — Política de privacidad',
  '',
  '**Versión 1.0 — Vigencia a partir del 23 de marzo de 2025**',
  '',
  'BrSpark Tecnologia Ltda. se compromete a proteger tu privacidad. Esta política describe cómo recopilamos, usamos y protegemos los datos personales, en línea con la **LGPD (Brasil)** y el **RGPD (UE)** cuando corresponda.',
  '',
  '## 1. Responsable del tratamiento',
  '**BrSpark Tecnologia Ltda.** — São Paulo, Brasil. DPO: **dpo@brspark.com**.',
  '',
  '## 2. Datos que recopilamos',
  '- Datos de registro (nombre, correo, hash de contraseña);',
  '- Datos operativos y de activos que elijas almacenar;',
  '- Registros de dispositivo, seguridad y diagnóstico necesarios para el servicio.',
  '',
  '## 3. Finalidades y bases legales',
  'Creación de cuenta, prestación del servicio, seguridad, prevención del fraude, cumplimiento legal y, cuando proceda, consentimiento para notificaciones.',
  '',
  '## 4. Cesiones',
  '**No vendemos** datos personales. Utilizamos proveedores de infraestructura y compartimos cuando la ley lo exija.',
  '',
  '## 5. Seguridad',
  'Cifrado en tránsito (TLS) y en reposo cuando aplique; contraseñas con hash robusto.',
  '',
  '## 6. Conservación',
  'Los plazos dependen del estado de la cuenta, obligaciones legales y necesidades operativas (véase la versión detallada en portugués si la necesitas).',
  '',
  '## 7. Tus derechos',
  'Acceso, rectificación, supresión, portabilidad, oposición y retirada del consentimiento cuando aplique — **dpo@brspark.com**.',
  '',
  '## 8. Cambios',
  'Los cambios sustanciales se notificarán con antelación razonable.',
  '',
  '---',
  '📧 **DPO**: dpo@brspark.com | 🌐 https://www.brspark.com',
].join('\n');
