/**
 * Biblioteca de ícones para ativos (Ionicons outline).
 * Gerado por scripts/generate-asset-icon-library.mjs — não edite à mão em massa.
 */
export type AssetIconEntry = { icon: string; label: string };

export const ASSET_ICON_LIBRARY: AssetIconEntry[] = [
  { icon: "home-outline", label: "Casa" },
  { icon: "business-outline", label: "Negócios" },
  { icon: "storefront-outline", label: "Loja" },
  { icon: "bed-outline", label: "Cama" },
  { icon: "car-outline", label: "Carro" },
  { icon: "boat-outline", label: "Barco" },
  { icon: "airplane-outline", label: "Avião" },
  { icon: "bicycle-outline", label: "Bicicleta" },
  { icon: "bus-outline", label: "Ônibus" },
  { icon: "train-outline", label: "Trem" },
  { icon: "wallet-outline", label: "Carteira" },
  { icon: "hardware-chip-outline", label: "Hardware · Chip" },
  { icon: "server-outline", label: "Servidor" },
  { icon: "desktop-outline", label: "Desktop" },
  { icon: "laptop-outline", label: "Notebook" },
  { icon: "phone-portrait-outline", label: "Telefone · Retrato" },
  { icon: "tablet-portrait-outline", label: "Tablet · Retrato" },
  { icon: "camera-outline", label: "Câmera" },
  { icon: "videocam-outline", label: "Vídeo" },
  { icon: "construct-outline", label: "Construção" },
  { icon: "hammer-outline", label: "Martelo" },
  { icon: "leaf-outline", label: "Folha" },
  { icon: "water-outline", label: "Água" },
  { icon: "flame-outline", label: "Chama" },
  { icon: "flash-outline", label: "Flash" },
  { icon: "battery-charging-outline", label: "Bateria · Carregando" },
  { icon: "medkit-outline", label: "Saúde" },
  { icon: "fitness-outline", label: "Fitness" },
  { icon: "school-outline", label: "Escola" },
  { icon: "library-outline", label: "Biblioteca" },
  { icon: "restaurant-outline", label: "Restaurante" },
  { icon: "cafe-outline", label: "Café" },
  { icon: "wine-outline", label: "Vinho" },
  { icon: "pizza-outline", label: "Pizza" },
  { icon: "musical-notes-outline", label: "Música · Notes" },
  { icon: "color-palette-outline", label: "Cor · Palette" },
  { icon: "image-outline", label: "Imagem" },
  { icon: "diamond-outline", label: "Diamante" },
  { icon: "shield-outline", label: "Escudo" },
  { icon: "key-outline", label: "Chave" },
  { icon: "lock-closed-outline", label: "Cadeado · Closed" },
  { icon: "globe-outline", label: "Globo" },
  { icon: "navigate-outline", label: "Navegar" },
  { icon: "map-outline", label: "Mapa" },
  { icon: "location-outline", label: "Local" },
  { icon: "trail-sign-outline", label: "Trilha · Sign" },
  { icon: "cube-outline", label: "Cubo" },
  { icon: "layers-outline", label: "Camadas" },
  { icon: "git-network-outline", label: "Git · Network" },
  { icon: "briefcase-outline", label: "Maleta" },
  { icon: "barbell-outline", label: "Halter" },
  { icon: "football-outline", label: "Futebol amer." },
  { icon: "basketball-outline", label: "Basquete" },
  { icon: "golf-outline", label: "Golfe" },
  { icon: "snow-outline", label: "Neve" },
  { icon: "rainy-outline", label: "Chuva" },
  { icon: "partly-sunny-outline", label: "Parcial · Sol" },
  { icon: "cloud-outline", label: "Nuvem" },
  { icon: "thunderstorm-outline", label: "Thunderstorm" },
  { icon: "accessibility-outline", label: "Acessibilidade" },
  { icon: "add-circle-outline", label: "Add · Circle" },
  { icon: "add-outline", label: "Add" },
  { icon: "alarm-outline", label: "Alarme" },
  { icon: "albums-outline", label: "Albums" },
  { icon: "alert-circle-outline", label: "Alert · Circle" },
  { icon: "alert-outline", label: "Alert" },
  { icon: "american-football-outline", label: "American · Futebol amer." },
  { icon: "analytics-outline", label: "Análises" },
  { icon: "aperture-outline", label: "Abertura" },
  { icon: "apps-outline", label: "Apps" },
  { icon: "archive-outline", label: "Arquivo" },
  { icon: "arrow-back-circle-outline", label: "Seta · Back · Circle" },
  { icon: "arrow-back-outline", label: "Seta · Back" },
  { icon: "arrow-down-circle-outline", label: "Seta · Down · Circle" },
  { icon: "arrow-down-left-box-outline", label: "Seta · Down · Left · Box" },
  { icon: "arrow-down-outline", label: "Seta · Down" },
  { icon: "arrow-down-right-box-outline", label: "Seta · Down · Right · Box" },
  { icon: "arrow-forward-circle-outline", label: "Seta · Forward · Circle" },
  { icon: "arrow-forward-outline", label: "Seta · Forward" },
  { icon: "arrow-redo-circle-outline", label: "Seta · Redo · Circle" },
  { icon: "arrow-redo-outline", label: "Seta · Redo" },
  { icon: "arrow-undo-circle-outline", label: "Seta · Undo · Circle" },
  { icon: "arrow-undo-outline", label: "Seta · Undo" },
  { icon: "arrow-up-circle-outline", label: "Seta · Up · Circle" },
  { icon: "arrow-up-left-box-outline", label: "Seta · Up · Left · Box" },
  { icon: "arrow-up-outline", label: "Seta · Up" },
  { icon: "arrow-up-right-box-outline", label: "Seta · Up · Right · Box" },
  { icon: "at-circle-outline", label: "Arroba · Circle" },
  { icon: "at-outline", label: "Arroba" },
  { icon: "attach-outline", label: "Anexo" },
  { icon: "backspace-outline", label: "Backspace" },
  { icon: "bag-add-outline", label: "Bolsa · Add" },
  { icon: "bag-check-outline", label: "Bolsa · Check" },
  { icon: "bag-handle-outline", label: "Bolsa · Handle" },
  { icon: "bag-outline", label: "Bolsa" },
  { icon: "bag-remove-outline", label: "Bolsa · Remover" },
  { icon: "balloon-outline", label: "Balão" },
  { icon: "ban-outline", label: "Bloquear" },
  { icon: "bandage-outline", label: "Bandagem" },
  { icon: "bar-chart-outline", label: "Bar · Chart" },
  { icon: "barcode-outline", label: "Código barras" },
  { icon: "baseball-outline", label: "Beisebol" },
  { icon: "basket-outline", label: "Cesta" },
  { icon: "battery-dead-outline", label: "Bateria · Dead" },
  { icon: "battery-full-outline", label: "Bateria · Full" },
  { icon: "battery-half-outline", label: "Bateria · Half" },
  { icon: "beaker-outline", label: "Béquer" },
  { icon: "beer-outline", label: "Cerveja" },
  { icon: "binoculars-outline", label: "Binoculars" },
  { icon: "bluetooth-outline", label: "Bluetooth" },
  { icon: "body-outline", label: "Corpo" },
  { icon: "bonfire-outline", label: "Fogueira" },
  { icon: "book-outline", label: "Livro" },
  { icon: "bookmark-outline", label: "Marcador" },
  { icon: "bookmarks-outline", label: "Bookmarks" },
  { icon: "bowling-ball-outline", label: "Boliche · Ball" },
  { icon: "browsers-outline", label: "Browsers" },
  { icon: "brush-outline", label: "Pincel" },
  { icon: "bug-outline", label: "Bug" },
  { icon: "build-outline", label: "Construir" },
  { icon: "bulb-outline", label: "Lâmpada" },
  { icon: "calculator-outline", label: "Calculadora" },
  { icon: "calendar-clear-outline", label: "Calendário · Clear" },
  { icon: "calendar-number-outline", label: "Calendário · Number" },
  { icon: "calendar-outline", label: "Calendário" },
  { icon: "call-outline", label: "Chamada" },
  { icon: "camera-reverse-outline", label: "Câmera · Reverse" },
  { icon: "car-sport-outline", label: "Carro · Sport" },
  { icon: "card-outline", label: "Cartão" },
  { icon: "caret-back-circle-outline", label: "Seta · Back · Circle" },
  { icon: "caret-back-outline", label: "Seta · Back" },
  { icon: "caret-down-circle-outline", label: "Seta · Down · Circle" },
  { icon: "caret-down-outline", label: "Seta · Down" },
  { icon: "caret-forward-circle-outline", label: "Seta · Forward · Circle" },
  { icon: "caret-forward-outline", label: "Seta · Forward" },
  { icon: "caret-up-circle-outline", label: "Seta · Up · Circle" },
  { icon: "caret-up-outline", label: "Seta · Up" },
  { icon: "cart-outline", label: "Carrinho" },
  { icon: "cash-outline", label: "Dinheiro" },
  { icon: "cellular-outline", label: "Celular" },
  { icon: "chatbox-ellipses-outline", label: "Chat · Ellipses" },
  { icon: "chatbox-outline", label: "Chat" },
  { icon: "chatbubble-ellipses-outline", label: "Mensagem · Ellipses" },
  { icon: "chatbubble-outline", label: "Mensagem" },
  { icon: "chatbubbles-outline", label: "Chatbubbles" },
  { icon: "checkbox-outline", label: "Checkbox" },
  { icon: "checkmark-circle-outline", label: "Confirmação · Circle" },
  { icon: "checkmark-done-circle-outline", label: "Confirmação · Done · Circle" },
  { icon: "checkmark-done-outline", label: "Confirmação · Done" },
  { icon: "checkmark-outline", label: "Confirmação" },
  { icon: "chevron-back-circle-outline", label: "Chevron · Back · Circle" },
  { icon: "chevron-back-outline", label: "Chevron · Back" },
  { icon: "chevron-collapse-outline", label: "Chevron · Collapse" },
  { icon: "chevron-down-circle-outline", label: "Chevron · Down · Circle" },
  { icon: "chevron-down-outline", label: "Chevron · Down" },
  { icon: "chevron-expand-outline", label: "Chevron · Expandir" },
  { icon: "chevron-forward-circle-outline", label: "Chevron · Forward · Circle" },
  { icon: "chevron-forward-outline", label: "Chevron · Forward" },
  { icon: "chevron-up-circle-outline", label: "Chevron · Up · Circle" },
  { icon: "chevron-up-outline", label: "Chevron · Up" },
  { icon: "clipboard-outline", label: "Área transf." },
  { icon: "close-circle-outline", label: "Fechar · Circle" },
  { icon: "close-outline", label: "Fechar" },
  { icon: "cloud-circle-outline", label: "Nuvem · Circle" },
  { icon: "cloud-done-outline", label: "Nuvem · Done" },
  { icon: "cloud-download-outline", label: "Nuvem · Download" },
  { icon: "cloud-offline-outline", label: "Nuvem · Offline" },
  { icon: "cloud-upload-outline", label: "Nuvem · Upload" },
  { icon: "cloudy-night-outline", label: "Nublado · Night" },
  { icon: "cloudy-outline", label: "Nublado" },
  { icon: "code-download-outline", label: "Código · Download" },
  { icon: "code-outline", label: "Código" },
  { icon: "code-slash-outline", label: "Código · Slash" },
  { icon: "code-working-outline", label: "Código · Working" },
  { icon: "cog-outline", label: "Engrenagem" },
  { icon: "color-fill-outline", label: "Cor · Fill" },
  { icon: "color-filter-outline", label: "Cor · Filtro" },
  { icon: "color-wand-outline", label: "Cor · Wand" },
  { icon: "compass-outline", label: "Bússola" },
  { icon: "contract-outline", label: "Contrato" },
  { icon: "contrast-outline", label: "Contraste" },
  { icon: "copy-outline", label: "Copiar" },
  { icon: "create-outline", label: "Criar" },
  { icon: "crop-outline", label: "Recortar" },
  { icon: "cut-outline", label: "Cortar" },
  { icon: "dice-outline", label: "Dado" },
  { icon: "disc-outline", label: "Disco" },
  { icon: "document-attach-outline", label: "Documento · Anexo" },
  { icon: "document-lock-outline", label: "Documento · Cadeado" },
  { icon: "document-outline", label: "Documento" },
  { icon: "document-text-outline", label: "Documento · Texto" },
  { icon: "documents-outline", label: "Documentos" },
  { icon: "download-outline", label: "Download" },
  { icon: "duplicate-outline", label: "Duplicar" },
  { icon: "ear-outline", label: "Ouvido" },
  { icon: "earth-outline", label: "Terra" },
  { icon: "easel-outline", label: "Cavalete" },
  { icon: "egg-outline", label: "Ovo" },
  { icon: "ellipse-outline", label: "Elipse" },
  { icon: "ellipsis-horizontal-circle-outline", label: "Reticências · Horizontal · Circle" },
  { icon: "ellipsis-horizontal-outline", label: "Reticências · Horizontal" },
  { icon: "ellipsis-vertical-circle-outline", label: "Reticências · Vertical · Circle" },
  { icon: "ellipsis-vertical-outline", label: "Reticências · Vertical" },
  { icon: "enter-outline", label: "Entrar" },
  { icon: "exit-outline", label: "Sair" },
  { icon: "expand-outline", label: "Expandir" },
  { icon: "extension-puzzle-outline", label: "Extensão · Puzzle" },
  { icon: "eye-off-outline", label: "Olho · Off" },
  { icon: "eye-outline", label: "Olho" },
  { icon: "eyedrop-outline", label: "Conta-gotas" },
  { icon: "fast-food-outline", label: "Comida rápida · Food" },
  { icon: "female-outline", label: "Feminino" },
  { icon: "file-tray-full-outline", label: "Arquivo · Tray · Full" },
  { icon: "file-tray-outline", label: "Arquivo · Tray" },
  { icon: "file-tray-stacked-outline", label: "Arquivo · Tray · Stacked" },
  { icon: "film-outline", label: "Filme" },
  { icon: "filter-circle-outline", label: "Filtro · Circle" },
  { icon: "filter-outline", label: "Filtro" },
  { icon: "finger-print-outline", label: "Digital · Impressão" },
  { icon: "fish-outline", label: "Peixe" },
  { icon: "flag-outline", label: "Bandeira" },
  { icon: "flash-off-outline", label: "Flash · Off" },
  { icon: "flashlight-outline", label: "Lanterna" },
  { icon: "flask-outline", label: "Frasco" },
  { icon: "flower-outline", label: "Flor" },
  { icon: "folder-open-outline", label: "Pasta · Abrir" },
  { icon: "folder-outline", label: "Pasta" },
  { icon: "footsteps-outline", label: "Passos" },
  { icon: "funnel-outline", label: "Funil" },
  { icon: "game-controller-outline", label: "Jogo · Controller" },
  { icon: "gift-outline", label: "Presente" },
  { icon: "git-branch-outline", label: "Git · Branch" },
  { icon: "git-commit-outline", label: "Git · Commit" },
  { icon: "git-compare-outline", label: "Git · Compare" },
  { icon: "git-merge-outline", label: "Git · Merge" },
  { icon: "git-pull-request-outline", label: "Git · Pull · Request" },
  { icon: "glasses-outline", label: "Óculos" },
  { icon: "grid-outline", label: "Grade" },
  { icon: "hand-left-outline", label: "Mão · Left" },
  { icon: "hand-right-outline", label: "Mão · Right" },
  { icon: "happy-outline", label: "Feliz" },
  { icon: "headset-outline", label: "Headset" },
  { icon: "heart-circle-outline", label: "Coração · Circle" },
  { icon: "heart-dislike-circle-outline", label: "Coração · Dislike · Circle" },
  { icon: "heart-dislike-outline", label: "Coração · Dislike" },
  { icon: "heart-half-outline", label: "Coração · Half" },
  { icon: "heart-outline", label: "Coração" },
  { icon: "help-buoy-outline", label: "Ajuda · Buoy" },
  { icon: "help-circle-outline", label: "Ajuda · Circle" },
  { icon: "help-outline", label: "Ajuda" },
  { icon: "hourglass-outline", label: "Ampulheta" },
  { icon: "ice-cream-outline", label: "Sorvete · Cream" },
  { icon: "id-card-outline", label: "ID · Cartão" },
  { icon: "images-outline", label: "Imagens" },
  { icon: "infinite-outline", label: "Infinite" },
  { icon: "information-circle-outline", label: "Info · Circle" },
  { icon: "information-outline", label: "Info" },
  { icon: "invert-mode-outline", label: "Inverter · Mode" },
  { icon: "journal-outline", label: "Diário" },
  { icon: "keypad-outline", label: "Teclado" },
  { icon: "language-outline", label: "Idioma" },
  { icon: "link-outline", label: "Link" },
  { icon: "list-circle-outline", label: "Lista · Circle" },
  { icon: "list-outline", label: "Lista" },
  { icon: "locate-outline", label: "Localizar" },
  { icon: "lock-open-outline", label: "Cadeado · Abrir" },
  { icon: "log-in-outline", label: "Log · In" },
  { icon: "log-out-outline", label: "Log · Out" },
  { icon: "magnet-outline", label: "Magnet" },
  { icon: "mail-open-outline", label: "E-mail · Abrir" },
  { icon: "mail-outline", label: "E-mail" },
  { icon: "mail-unread-outline", label: "E-mail · Unread" },
  { icon: "male-female-outline", label: "Masculino · Feminino" },
  { icon: "male-outline", label: "Masculino" },
  { icon: "man-outline", label: "Homem" },
  { icon: "medal-outline", label: "Medalha" },
  { icon: "medical-outline", label: "Medical" },
  { icon: "megaphone-outline", label: "Megafone" },
  { icon: "menu-outline", label: "Menu" },
  { icon: "mic-circle-outline", label: "Microfone · Circle" },
  { icon: "mic-off-circle-outline", label: "Microfone · Off · Circle" },
  { icon: "mic-off-outline", label: "Microfone · Off" },
  { icon: "mic-outline", label: "Microfone" },
  { icon: "moon-outline", label: "Lua" },
  { icon: "move-outline", label: "Mover" },
  { icon: "musical-note-outline", label: "Música · Note" },
  { icon: "navigate-circle-outline", label: "Navegar · Circle" },
  { icon: "newspaper-outline", label: "Jornal" },
  { icon: "notifications-circle-outline", label: "Notificação · Circle" },
  { icon: "notifications-off-circle-outline", label: "Notificação · Off · Circle" },
  { icon: "notifications-off-outline", label: "Notificação · Off" },
  { icon: "notifications-outline", label: "Notificação" },
  { icon: "nuclear-outline", label: "Nuclear" },
  { icon: "nutrition-outline", label: "Nutrição" },
  { icon: "open-outline", label: "Abrir" },
  { icon: "options-outline", label: "Opções" },
  { icon: "paper-plane-outline", label: "Papel · Plane" },
  { icon: "pause-circle-outline", label: "Pausa · Circle" },
  { icon: "pause-outline", label: "Pausa" },
  { icon: "paw-outline", label: "Pata" },
  { icon: "pencil-outline", label: "Lápis" },
  { icon: "people-circle-outline", label: "Pessoas · Circle" },
  { icon: "people-outline", label: "Pessoas" },
  { icon: "person-add-outline", label: "Pessoa · Add" },
  { icon: "person-circle-outline", label: "Pessoa · Circle" },
  { icon: "person-outline", label: "Pessoa" },
  { icon: "person-remove-outline", label: "Pessoa · Remover" },
  { icon: "phone-landscape-outline", label: "Telefone · Paisagem" },
  { icon: "pie-chart-outline", label: "Pizza gráf. · Chart" },
  { icon: "pin-outline", label: "Alfinete" },
  { icon: "pint-outline", label: "Caneca" },
  { icon: "planet-outline", label: "Planeta" },
  { icon: "play-back-circle-outline", label: "Play · Back · Circle" },
  { icon: "play-back-outline", label: "Play · Back" },
  { icon: "play-circle-outline", label: "Play · Circle" },
  { icon: "play-forward-circle-outline", label: "Play · Forward · Circle" },
  { icon: "play-forward-outline", label: "Play · Forward" },
  { icon: "play-outline", label: "Play" },
  { icon: "play-skip-back-circle-outline", label: "Play · Skip · Back · Circle" },
  { icon: "play-skip-back-outline", label: "Play · Skip · Back" },
  { icon: "play-skip-forward-circle-outline", label: "Play · Skip · Forward · Circle" },
  { icon: "play-skip-forward-outline", label: "Play · Skip · Forward" },
  { icon: "podium-outline", label: "Pódio" },
  { icon: "power-outline", label: "Energia" },
  { icon: "pricetag-outline", label: "Etiqueta" },
  { icon: "pricetags-outline", label: "Pricetags" },
  { icon: "print-outline", label: "Impressão" },
  { icon: "prism-outline", label: "Prisma" },
  { icon: "pulse-outline", label: "Pulso" },
  { icon: "push-outline", label: "Push" },
  { icon: "qr-code-outline", label: "QR · Código" },
  { icon: "radio-button-off-outline", label: "Rádio · Button · Off" },
  { icon: "radio-button-on-outline", label: "Rádio · Button · On" },
  { icon: "radio-outline", label: "Rádio" },
  { icon: "reader-outline", label: "Leitor" },
  { icon: "receipt-outline", label: "Recibo" },
  { icon: "recording-outline", label: "Gravação" },
  { icon: "refresh-circle-outline", label: "Atualizar · Circle" },
  { icon: "refresh-outline", label: "Atualizar" },
  { icon: "reload-circle-outline", label: "Reload · Circle" },
  { icon: "reload-outline", label: "Reload" },
  { icon: "remove-circle-outline", label: "Remover · Circle" },
  { icon: "remove-outline", label: "Remover" },
  { icon: "reorder-four-outline", label: "Reordenar · Four" },
  { icon: "reorder-three-outline", label: "Reordenar · Three" },
  { icon: "reorder-two-outline", label: "Reordenar · Two" },
  { icon: "repeat-outline", label: "Repetir" },
  { icon: "resize-outline", label: "Redimensionar" },
  { icon: "return-down-back-outline", label: "Return · Down · Back" },
  { icon: "return-down-forward-outline", label: "Return · Down · Forward" },
  { icon: "return-up-back-outline", label: "Return · Up · Back" },
  { icon: "return-up-forward-outline", label: "Return · Up · Forward" },
  { icon: "ribbon-outline", label: "Fita" },
  { icon: "rocket-outline", label: "Foguete" },
  { icon: "rose-outline", label: "Rosa" },
  { icon: "sad-outline", label: "Triste" },
  { icon: "save-outline", label: "Salvar" },
  { icon: "scale-outline", label: "Balança" },
  { icon: "scan-circle-outline", label: "Escanear · Circle" },
  { icon: "scan-outline", label: "Escanear" },
  { icon: "search-circle-outline", label: "Buscar · Circle" },
  { icon: "search-outline", label: "Buscar" },
  { icon: "send-outline", label: "Enviar" },
  { icon: "settings-outline", label: "Ajustes" },
  { icon: "shapes-outline", label: "Formas" },
  { icon: "share-outline", label: "Compartilhar" },
  { icon: "share-social-outline", label: "Compartilhar · Social" },
  { icon: "shield-checkmark-outline", label: "Escudo · Confirmação" },
  { icon: "shield-half-outline", label: "Escudo · Half" },
  { icon: "shirt-outline", label: "Camisa" },
  { icon: "shuffle-outline", label: "Embaralhar" },
  { icon: "skull-outline", label: "Caveira" },
  { icon: "sparkles-outline", label: "Brilhos" },
  { icon: "speedometer-outline", label: "Velocímetro" },
  { icon: "square-outline", label: "Quadrado" },
  { icon: "star-half-outline", label: "Estrela · Half" },
  { icon: "star-outline", label: "Estrela" },
  { icon: "stats-chart-outline", label: "Estatísticas · Chart" },
  { icon: "stop-circle-outline", label: "Stop · Circle" },
  { icon: "stop-outline", label: "Stop" },
  { icon: "stopwatch-outline", label: "Cronômetro" },
  { icon: "subway-outline", label: "Metrô" },
  { icon: "sunny-outline", label: "Sol" },
  { icon: "swap-horizontal-outline", label: "Trocar · Horizontal" },
  { icon: "swap-vertical-outline", label: "Trocar · Vertical" },
  { icon: "sync-circle-outline", label: "Sincronizar · Circle" },
  { icon: "sync-outline", label: "Sincronizar" },
  { icon: "tablet-landscape-outline", label: "Tablet · Paisagem" },
  { icon: "telescope-outline", label: "Telescópio" },
  { icon: "tennisball-outline", label: "Tennisball" },
  { icon: "terminal-outline", label: "Terminal" },
  { icon: "text-outline", label: "Texto" },
  { icon: "thermometer-outline", label: "Termômetro" },
  { icon: "thumbs-down-outline", label: "Polegar · Down" },
  { icon: "thumbs-up-outline", label: "Polegar · Up" },
  { icon: "ticket-outline", label: "Ingresso" },
  { icon: "time-outline", label: "Tempo" },
  { icon: "timer-outline", label: "Timer" },
  { icon: "today-outline", label: "Hoje" },
  { icon: "toggle-outline", label: "Alternar" },
  { icon: "transgender-outline", label: "Transgênero" },
  { icon: "trash-bin-outline", label: "Lixeira · Bin" },
  { icon: "trash-outline", label: "Lixeira" },
  { icon: "trending-down-outline", label: "Tendência · Down" },
  { icon: "trending-up-outline", label: "Tendência · Up" },
  { icon: "triangle-outline", label: "Triângulo" },
  { icon: "trophy-outline", label: "Troféu" },
  { icon: "tv-outline", label: "TV" },
  { icon: "umbrella-outline", label: "Guarda-chuva" },
  { icon: "unlink-outline", label: "Desvincular" },
  { icon: "videocam-off-outline", label: "Vídeo · Off" },
  { icon: "volume-high-outline", label: "Volume · High" },
  { icon: "volume-low-outline", label: "Volume · Low" },
  { icon: "volume-medium-outline", label: "Volume · Medium" },
  { icon: "volume-mute-outline", label: "Volume · Mute" },
  { icon: "volume-off-outline", label: "Volume · Off" },
  { icon: "walk-outline", label: "Caminhar" },
  { icon: "warning-outline", label: "Alerta" },
  { icon: "watch-outline", label: "Relógio" },
  { icon: "wifi-outline", label: "Wi‑Fi" },
  { icon: "woman-outline", label: "Mulher" },
];

/** Total de ícones disponíveis */
export const ASSET_ICON_LIBRARY_COUNT = ASSET_ICON_LIBRARY.length;
