-- Expansão do módulo de Compliance para governança legal multi-país, multi-audiência e app mobile.
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'MOBILE_EULA';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'LOCATION_NOTICE';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'BIOMETRIC_NOTICE';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'WORK_TIME_POLICY';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'AI_USAGE_POLICY';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'DATA_RETENTION_POLICY';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SUBPROCESSORS_LIST';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SLA_SUPPORT_POLICY';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'BILLING_REFUND_POLICY';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'PROVIDER_TERMS';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'KYC_NOTICE';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'ACCEPTABLE_USE_POLICY';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SECURITY_POLICY';

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ComplianceReviewStatus') THEN
    CREATE TYPE "ComplianceReviewStatus" AS ENUM ('DRAFT', 'LEGAL_REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED');
  END IF;
END $$;

ALTER TABLE "ComplianceDoc"
  ADD COLUMN IF NOT EXISTS "effectiveFrom" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "reviewStatus" "ComplianceReviewStatus" NOT NULL DEFAULT 'DRAFT',
  ADD COLUMN IF NOT EXISTS "reviewedBy" TEXT,
  ADD COLUMN IF NOT EXISTS "reviewedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "archivedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "changeSummary" TEXT,
  ADD COLUMN IF NOT EXISTS "audience" TEXT NOT NULL DEFAULT 'ALL',
  ADD COLUMN IF NOT EXISTS "platform" TEXT NOT NULL DEFAULT 'ALL',
  ADD COLUMN IF NOT EXISTS "jurisdiction" TEXT NOT NULL DEFAULT 'GLOBAL',
  ADD COLUMN IF NOT EXISTS "legalBasis" TEXT,
  ADD COLUMN IF NOT EXISTS "requiresAcceptance" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "blocking" BOOLEAN NOT NULL DEFAULT true;

UPDATE "ComplianceDoc"
SET "reviewStatus" = CASE WHEN "isActive" THEN 'PUBLISHED'::"ComplianceReviewStatus" ELSE "reviewStatus" END,
    "effectiveFrom" = COALESCE("effectiveFrom", "publishedAt")
WHERE "isActive" = true;
